### ISSUE TITLE
Add static page explaining payment details

### ISSUE THREAD

**Issue by nlokare** [hesitant-tapdancers/gilded#220]

**Comment by dsernst** [comment]
lets start drafting out what this payment needs to say

**Comment by dsernst** [comment]
* How can senders pay? Credit card or Bitcoin
* How is payment information protected? For your protection, everything is sent over encrypted SSL. All payment information is securely stored by Stripe (The same system used by Apple Pay). PCI Compliant.
* How balance is calculated: 70% at time of withdraw, minus $0.25 fee from Stripe.
* Stripe fees: $0.30 + 0.29%, paid by sender
* How to withdraw: Add a debit card on your Payment Settings page.
