### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by bcbcb** [hesitant-tapdancers/gilded#247]

**Comment by nlokare** [comment]
Use MongoGridFS to store attachments and retrieve them when releasing emails from escrow.

**Comment by nlokare** [comment]
Multiple attachments from VIPs are sent along smoothly. One attachment is successfully working from escrow, but need to work on handling 2+

**Comment by nlokare** [comment]
Fixed cases without attachments. They weren't sending. Will make a pull request tomorrow
