### ISSUE TITLE
redirect to https on production

### ISSUE THREAD

**Issue by dsernst** [hesitant-tapdancers/gilded#256]

**Comment by dsernst** [comment]
If they hit [gilded.club](http://gilded.club), they will be redirected to https://www.gilded.club . http://www.gilded.club does not currently direct to `https`. And https://gilded.club just straight up doesn't work.

If in doubt, use https://www.gilded.club or http://gilded.club

**Comment by dsernst** [comment]
Hmm, well I thought https://gilded.club wouldn't work, but now that I'm testing it, it seems to be redirecting to https://www.gilded.club. :dancer: Are y'all seeing the same?

**Comment by dsernst** [comment]
So to recap:

* http://gilded.club  -> https://www.gilded.club good
* https://gilded.club  -> https://www.gilded.club good
* http://www.gilded.club  **No redirection**.
* https://www.gilded.club good

**Comment by bcbcb** [comment]
https://stackoverflow.com/questions/4723213/detect-http-or-https-then-force-https-in-javascript

**Comment by dsernst** [comment]
priority:

bren: 8   
neil: 9  
christian: 7   
david: 7

**Comment by dsernst** [comment]
done. 

CloudFlare actually made this super easy with their [PageRules feature](https://support.cloudflare.com/hc/en-us/articles/200172286-How-do-I-do-url-forwarding-with-CloudFlare-), so this is happening on the server instead of in the client. Even better, load wise.

**Comment by dsernst** [comment]
now all combinations of https vs http, and naked domain vs www. end up at https://www.gilded.club

**Comment by dsernst** [comment]
![screen shot 2015-03-02 at 12 32 50 pm](https://cloud.githubusercontent.com/assets/6340841/6449801/51e5117e-c0d8-11e4-9f33-a61a59f92b93.png)
