### ISSUE TITLE
match payment page style to rest of site

### ISSUE THREAD

**Issue by dsernst** [hesitant-tapdancers/gilded#346]
- [ ] Gilded logo color
- [ ] Pay with card button

**Comment by dsernst** [comment]
- [ ] background?

**Comment by nlokare** [comment]
background changed, button is a no go. Major inline script issues with jade and requires a bunch of reconfiguring our server to make the requests to stripe after a token is returned.

**Comment by nlokare** [comment]
font colors changed as well to match the rest of the site
